services:
    _defaults:
        public: false

    Runroom\TranslationBundle\Service\TranslationService:
        arguments:
            $translator: '@translator'
            $cache: '@Runroom\TranslationBundle\Service\TranslationCacheService'
            $requestStack: '@request_stack'

    Runroom\TranslationBundle\Service\TranslationCacheService:
        public: false
        arguments:
            $repository: '@Runroom\TranslationBundle\Repository\TranslationRepository'
            $cache: '@Symfony\Component\Cache\Adapter\PhpArrayAdapter'
        tags:
            - { name: kernel.cache_warmer, priority: 0 }
            - kernel.cache_clearer

    Runroom\TranslationBundle\Twig\TranslationExtension:
        arguments:
            $service: '@Runroom\TranslationBundle\Service\TranslationService'
        tags: [twig.extension]

    Runroom\TranslationBundle\Repository\TranslationRepository:
        public: false
        arguments: ['@Doctrine\ORM\EntityManagerInterface']

    Runroom\TranslationBundle\Command\TranslationCommand:
        public: false
        arguments:
            $translator: '@translator'
            $repository: '@Runroom\TranslationBundle\Repository\TranslationRepository'
            $cache: '@Runroom\TranslationBundle\Service\TranslationCacheService'
            $locales: '%locales%'
        tags: [console.command]

    Symfony\Component\Cache\Adapter\PhpArrayAdapter:
        arguments:
            - '%kernel.cache_dir%/translations.cache.php'
            - '@Symfony\Component\Cache\Adapter\ArrayAdapter'

    Symfony\Component\Cache\Adapter\ArrayAdapter: ~
