services:
    _defaults:
        public: false

    Runroom\TranslationBundle\Service\TranslationService:
        arguments:
            $repository: '@Doctrine\ORM\EntityRepository'
            $translator: '@translator'

    Runroom\TranslationBundle\Twig\TranslationExtension:
        arguments:
            $service: '@Runroom\TranslationBundle\Service\TranslationService'
        tags: [twig.extension]

    Doctrine\ORM\EntityRepository:
        factory: ['@Doctrine\ORM\EntityManagerInterface', getRepository]
        arguments: [Runroom\TranslationBundle\Entity\Translation]
